### ISSUE TITLE
mejorar el gitignore para que no ignore `src/client` en proyectos con TS

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/codenautas#5]
Ahora en los procyectos que tienen TypeScript les estamos poniend `client` y `server` en el `.gitignore` porque son los compilados. 

Habría que especificar que son solo los `client` y `server` colgando del raíz.

Empezar en `procesamiento`

**Comment by euginio** [comment]
Se hizo en todos los 4 proyectos dependencias
